### ISSUE TITLE
Review Language: Telugu (Python)

### ISSUE THREAD

**Issue by madiedgar** [legesher/legesher-translations#172]
## Review Telugu Translations for Python

In order to review this language to the project, complete the steps detailed in the [translation guide](https://docs.legesher.io/legesher-translations/translation-guide) (from Step #6 onward). We are primarily working developing Legesher for the Python programming language. In the future we hope to add more programming languages in the future.

**Reviewing** a translation is extremely important as we want to best understand the culture and context behind the words we select as keywords for the programming languages. The more perspectives the better! 👀Please take your time in being thorough with these translations. Think back when you were learning how to program and how context of words help you bridge together meaning and functionality.

> ⚠️ Note: this issue is to review the Python keywords and builtin functions only. Any additional translation reviews are encouraged, but not necessary.

**To complete this issue**:

- [x] Update any content in this issue from `LANGUAGE` to the name of the language. (Romanian, Arabic, Welsh etc.)
- [x] Title this issue "Review Language: Telugu (Python)"
- [x] Update the Python section of the LANGUAGE's `locale/__.yml` file (files are named using the language abbreviation) by adding comments as followed.

  - **Agreeable:** Leave a `# @username ✅_with any additional commentary afterwards_` after a translation if you agree that the right word to give context to the keyword is the one initially translated.
  - **Optimistic:** Leave a `# @username ❓_with any additional commentary afterwards_` after a translation if you think there may be a better translation / form of the translation
  - **Unsure:** Leave a `# @username 🤔_with any additional commentary afterwards_` after a word that you're not sure if there is a translation

  This issue will be complete when all the words for a programming language looks something like this:

  ```yml
  int: "initiatorsTranslation" # ✅ @firstreviewer, ❓@secondreviewer what about this otherTranslation, ❓@thirdreviewer I agree with otherTranslation, ✅ @fourthreviewer, ✅ @fifthreviewer I also think otherTranslation would be a good option
  ```

- [x] Merge changes into branch titled `telugu-translation` on this repo, **NOT** the `master` branch. Please reference this issue in the pull request.

### Reviewers Needed

In order to add the translations for official use across Legesher, the translations will need to be approved and accepted by **5 additional native / fluent speakers**. If you would like to be one of the reviewers for this language, please mention in this issue! :smile: Also feel free to loop in a friend that might be able to help with the translations! Please refer to the [translation guide](https://docs.legesher.io/legesher-translations/translation-guide) for the next step in the review process.

**Review Status**:

- [x] `Add New Dialect` Issue (#127) 
- [x] Initiator: @nagendrady (#140) 
- [x] Reviewer 1: @manojkrishnak (#224)
- [x] Reviewer 2: @Sujithkumardola (#300)
- [x] Reviewer 3: @Ln11211 (#258)
- [x] Reviewer 4: @KarthikMothiki (#275)
- [x] Reviewer 5: @sneha-thyagarajan (#308)
- [x] Reviewer 6: @sh1fu-X (#309, #310)

**Comment by manojkrishnak** [comment]
Hi, i would like to take this up. 

I do have few doubts can I ping you on any platform? Discord?

**Comment by madiedgar** [comment]
Absolutely! I'll assign you for now and feel free to message me on discord. I'd love to hear your thoughts 👍

**Comment by manojkrishnak** [comment]
Hi @madiedgar i could not find you on Discord, can you give me your username?

**Comment by manojkrishnak** [comment]
Hi @madiedgar, I tried contacting you on Discord, seems like you have disabled DMs without being friend there, could you pls allow me to send messages?

**Comment by Ln11211** [comment]
@madiedgar, Like I promised, I want to review "Telugu", Can I start with reviewing ?

**Comment by Ln11211** [comment]
@madiedgar Can I please translate JAVA keywords into Telugu and Hindi?

**Comment by madiedgar** [comment]
Hi @Ln11211 👋 , could you actually start the initial translation of the Python Builtin functions instead? That would be extremely helpful!

**Comment by KarthikMothiki** [comment]
@madiedgar I translated built-in functions and keywords into Telugu. Created a PR!

**Comment by Sujithkumardola** [comment]
hey @madiedgar, i would like to contribute to this project.

**Comment by madiedgar** [comment]
Happy October @Sujithkumardola, @Ln11211, @KarthikMothiki, @manojkrishnak, and @nagendrady, thank you for your early support on this project! I'm excited about adding the Telugu translation to Legesher, but I could use your assistance in gathering enough reviewers. Would you consider reaching out to your friends or peers who share an interest and invite them to join us? 😄 Thank you!

**Comment by KarthikMothiki** [comment]
Sure @madiedgar, I'll recommend my peers to review the project.

**Comment by sh1fu-X** [comment]
Hello @madiedgar,

I'm excited to contribute to the Telugu translation for Legesher! Count me in. Let me know where I can get started.

**Comment by sneha-thyagarajan** [comment]
Hello @madiedgar , I'm glad to hear that you are adding Telugu translation to Legesher. I'm definitely interested in reviewing them

**Comment by sneha-thyagarajan** [comment]
Hello @madiedgar, I've completed my review of the Telugu translations. The translations are nearly perfect, and I've included alternative word choices in the comments where I thought they were needed.  Created a PR!

**Comment by madiedgar** [comment]
@sneha-thyagarajan your PR looks great, I just left a review. 
@sh1fu-X start by creating a branch from the `telugu-translation` branch. Add your review based off the information from this [translation guide](https://docs.legesher.io/legesher-translations/translation-guide). When you complete the python keywords and built-in functions raise a PR. 😄

**Comment by sh1fu-X** [comment]
Hello @madiedgar, I've finished reviewing the Telugu translations and have offered suggestions where they appeared necessary.

**Comment by madiedgar** [comment]
We've reached our requirement for reviewers on the Python keywords and built-in functions! 🎉 Be on the lookout for an Official Review PR for Telugu  👀

**Comment by sneha-thyagarajan** [comment]
Hey @madiedgar, I'm glad I could help with this issue. I'm happy to work on Telugu translations and reviews for other programming languages as well. Count me in if you need help with this in the future.
